name: Monthly Colour Update

on:
    workflow_dispatch:
    schedule:
        - cron: '0 0 1 * *'

jobs:
    UpdateColour:
        name: Update Colour
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4.1.6

            - name: Setup .NET
              uses: actions/setup-dotnet@v4.0.0

            - name: Restore .NET Tools
              run: dotnet tool restore

            - name: Update
              run: dotnet dotnet-script pick_colour.csx

            - name: Commit
              run: |
                  echo Updating colour for $(date +%B) $(date +%Y)
