name: Monthly Colour Update

on:
    workflow_dispatch:
    schedule:
        - cron: '0 0 1 * *'

jobs:
    UpdateColour:
        name: Update Colour
        runs-on: ubuntu-latest

        permissions:
            actions: write
            contents: write

        steps:
            - name: Checkout
              uses: actions/checkout@v4.1.6

            - name: Echo run info
              id: run_info
              run: |
                  echo Run ID $env.GITHUB_RUN_ID
                  echo Run number $env.GITHUB_RUN_NUMBER
                  echo Run attempt $env.GITHUB_RUN_ATTEMPT

            - name: Setup .NET
              uses: actions/setup-dotnet@v4.0.0

            - name: Restore .NET Tools
              run: dotnet tool restore

            - name: Update
              id: color_selector
              run: dotnet dotnet-script pick_colour.csx

            - uses: planetscale/ghcommit-action@v0.1.39
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  SELECTED_COLOR: ${{ steps.color_selector.outputs.selected_colour }}
                  RELEASE_DATE: ${{ steps.color_selector.outputs.release_date }}
              with:
                  commit_message: 'Colour of the month ${{ env.RELEASE_DATE }}: ${{ env.SELECTED_COLOR }}'
                  repo: ${{ github.repository }}
                  branch: ${{ github.head_ref || github.ref_name }}

    CallUpdateApp:
        name: Call Update App
        needs: UpdateColour
        uses: ./.github/workflows/update_app.yml
