name: Monthly Colour Update

on:
    workflow_dispatch:
    schedule:
        - cron: '0 0 1 * *'

jobs:
    UpdateColour:
        name: Update Colour
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4.1.6

            - name: Setup .NET
              uses: actions/setup-dotnet@v4.0.0

            - name: Restore .NET Tools
              run: dotnet tool restore

            - name: Update
              id: color_selector
              run: dotnet dotnet-script pick_colour.csx

            - name: Commit
              env:
                  SELECTED_COLOR: ${{ steps.color_selector.outputs.selected_colour }}
              run: |
                  echo Colour of the month $(date +%B) $(date +%Y): $SELECTED_COLOR
