name: Monthly Colour Update

on:
    workflow_dispatch:
    schedule:
        - cron: '0 0 1 * *'

jobs:
    UpdateColour:
        name: Update Colour
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4.1.6
              with:
                  token: ${{ secrets.PAT }}

            - name: Setup .NET
              uses: actions/setup-dotnet@v4.0.0

            - name: Restore .NET Tools
              run: dotnet tool restore

            - name: Update
              id: color_selector
              run: dotnet dotnet-script pick_colour.csx

            - name: Import GPG
              uses: crazy-max/ghaction-import-gpg@v6.1.0
              with:
                  gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
                  passphrase: ${{ secrets.PASSPHRASE }}
                  git_user_signingkey: true

            - name: Commit
              run: |
                  git add colours.csv
                  git commit -S -m "Bot: Colour of the month $(date +%B) $(date +%Y): $SELECTED_COLOR"
                  git push
