name: Monthly Colour Update

on:
    workflow_dispatch:
    schedule:
        - cron: '0 0 1 * *'

jobs:
    UpdateColour:
        name: Update Colour
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4.1.6

            - name: Setup .NET
              uses: actions/setup-dotnet@v4.0.0

            - name: Restore .NET Tools
              run: dotnet tool restore

            - name: Update
              id: color_selector
              run: dotnet dotnet-script pick_colour.csx

            - name: Set month and year
              id: set_date
              run: |
                  echo "month=$(date +'%B')" >> $GITHUB_OUTPUT
                  echo "year=$(date +'%Y')" >> $GITHUB_OUTPUT

            - uses: planetscale/ghcommit-action@v0.1.39
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  SELECTED_COLOR: ${{ steps.color_selector.outputs.selected_colour }}
                  MONTH: ${{ steps.set_date.outputs.month }}
                  YEAR: ${{ steps.set_date.outputs.year }}
              with:
                  commit_message: 'Colour of the month ${{ env.MONTH }} ${{ env.YEAR }}: ${{ env.SELECTED_COLOR }}'
                  repo: ${{ github.repository }}
                  branch: ${{ github.head_ref || github.ref_name }}
