name: Update App from main

on:
    workflow_call:
    push:
        branches: [ main ]

jobs:
    UpdateColour:
        name: Update App
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4.1.6
              with:
                  ref: ${{ github.ref }}

            - name: Echo run info
              id: run_info
              run: |
                  echo Run ID $env.GITHUB_RUN_ID
                  echo Run number $env.GITHUB_RUN_NUMBER
                  echo Run attempt $env.GITHUB_RUN_ATTEMPT

            - name: Update
              run: echo Updating app!
