name: Update App from main

on:
    workflow_call:
    push:
        branches: [ main ]

jobs:
    UpdateColour:
        name: Update App
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4.1.6
              with:
                  ref: ${{ github.ref }}

            - name: Setup .NET
              uses: actions/setup-dotnet@v4.0.0

            - name: Restore .NET Tools
              run: dotnet tool restore

            - name: Update Icon
              run: dotnet dotnet-script update_icon.csx

            - name: Update Icon
              run: dotnet dotnet-script update_version.csx
